version: "3.9"

networks:
  large-application-template:

volumes:
  large-application-template-backend-cache:
  large-application-template-db-volume:

x-shared: &database-environment-credentials
    POSTGRES_DB_HOST: "large-application-template-db"
    POSTGRES_DB_PORT: 5432
    POSTGRES_DB_NAME: "large_application_template"
    POSTGRES_DB_USER: "large_application_template_user"
    POSTGRES_DB_PASSWORD: "large_application_template_password"

services:
  large-application-template-db:
    restart: "no"
    image: "postgres:15-alpine"
    container_name: large-application-template-db-development
    networks:
      large-application-template:
    ports:
        - "5432:5432"
    volumes:
      - "large-application-template-db-volume:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "large_application_template_password"
      POSTGRES_USER: "large_application_template_user"
      POSTGRES_DB: "large_application_template"
    env_file:
      - ".env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  large-application-template-broker:
    restart: "no"
    image: "redis:5.0.0"
    container_name: large-application-template-broker-development
    networks:
      large-application-template:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  large-application-template-backend:
    restart: "no"
    build:
      context: ../../backend/
      dockerfile: ../docker/development/backend/Dockerfile
    container_name: large-application-template-backend-development
    depends_on:
      large-application-template-db:
        condition: service_healthy
      large-application-template-broker:
        condition: service_healthy
    networks:
      large-application-template:
    ports:
        - "8000:8000"  # Application port.
        - "8089:8089"  # Performance monitoring port.
    volumes:
      - "../../backend/:/app/"
      - "./backend/scripts/:/scripts/"
      - "large-application-template-backend-cache:/root/.cache/pip"
    environment:
      <<: *database-environment-credentials
      BROKER_URL: "redis://large-application-template-broker:6379/0"
    env_file:
      - ".env"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8000/health-check || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    command: ["/scripts/run-development.sh"]

  large-application-template-worker:
    restart: "no"
    build:
      context: ../../backend/
      dockerfile: ../docker/development/backend/Dockerfile
    container_name: large-application-template-worker-development
    depends_on:
      large-application-template-broker:
        condition: service_healthy
    networks:
      large-application-template:
    volumes:
      - "../../backend/:/app/"
      - "./backend/scripts/:/scripts/"
      - "large-application-template-backend-cache:/root/.cache/pip"
    environment:
      BROKER_URL: "redis://large-application-template-broker:6379/0"
    env_file:
      - ".env"
    healthcheck:
      test: ["CMD", "celery", "-A", "celery-task-dispatcher", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: ["/scripts/run-worker.sh"]
