import os
from pathlib import Path

SWAGGER_FILES = os.path.join(Path(__file__).parent.parent.parent, "swagger_files")

PAGINATION_LIMIT_QUERY_PARAMETER_NAME = "limit"
PAGINATION_OFFSET_QUERY_PARAMETER_NAME = "offset"
PAGINATION_TOTAL_COUNT_NAME = "count"
PAGINATION_NEXT_LINK_RELATION = "next"
PAGINATION_PREVIOUS_LINK_RELATION = "previous"
PAGINATION_RESULTS_NAME = "results"
ORDERING_QUERY_PARAMETER_NAME = "ordering"

ERROR_RESPONSE_KEY_DETAILS_NAME = "detail"
